name: Download Steam Workshop Dependencies
description: Downloads Steam Workshop items required for the project.
inputs:
  path:
    required: false
    default: ''
    description: 'The path of the directory to be uploaded, relative to the repository root.'
runs:
  using: composite
  shell: bash
  steps:
  - name: Download Steam Workshop Items with Docker
    run: |
      cd ${{ inputs.path }}

      docker run --rm \
        -v $(pwd):/workspace \
        -w /workspace \
        steamcmd/steamcmd:ubuntu-22 \
        ${{ github.action_path }}/setup.sh